"""Build and send the HTML newsletter email."""
import smtplib
import ssl
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from jinja2 import Template

import config

# ── HTML template ──────────────────────────────────────────────────────────────
_HTML_TEMPLATE = Template("""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body        { font-family: -apple-system, Arial, sans-serif; max-width: 680px;
                margin: 0 auto; padding: 24px; color: #1a1a1a; background: #f9f9f9; }
  h1          { font-size: 22px; color: #2c3e50; border-bottom: 2px solid #3498db;
                padding-bottom: 8px; }
  .meta       { color: #888; font-size: 13px; margin-bottom: 28px; }
  .summary    { background: #fff; border-radius: 8px; padding: 20px 24px;
                box-shadow: 0 1px 4px rgba(0,0,0,.08); line-height: 1.7; }
  .summary h2 { font-size: 16px; color: #2c3e50; margin-top: 24px; }
  .summary strong { color: #2980b9; }
  .footer     { margin-top: 32px; font-size: 12px; color: #aaa; text-align: center; }
  hr          { border: none; border-top: 1px solid #eee; margin: 20px 0; }
</style>
</head>
<body>
  <h1>📬 {{ subject }}</h1>
  <p class="meta">
    Period: <strong>{{ period_start }}</strong> → <strong>{{ period_end }}</strong>
    &nbsp;|&nbsp; {{ email_count }} email(s) processed
  </p>
  <div class="summary">
    {{ summary_html }}
  </div>
  <div class="footer">
    Generated by EmailBot &bull; {{ generated_at }}
  </div>
</body>
</html>
""")


def _markdown_to_html(md: str) -> str:
    """Minimal Markdown → HTML for bold, headers, bullets, and paragraphs."""
    import re
    lines = md.split("\n")
    html_lines = []
    in_ul = False

    for line in lines:
        stripped = line.strip()

        # Headings
        if stripped.startswith("### "):
            if in_ul: html_lines.append("</ul>"); in_ul = False
            html_lines.append(f"<h3>{stripped[4:]}</h3>")
        elif stripped.startswith("## "):
            if in_ul: html_lines.append("</ul>"); in_ul = False
            html_lines.append(f"<h2>{stripped[3:]}</h2>")
        elif stripped.startswith("# "):
            if in_ul: html_lines.append("</ul>"); in_ul = False
            html_lines.append(f"<h2>{stripped[2:]}</h2>")

        # Bullets
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_ul: html_lines.append("<ul>"); in_ul = True
            html_lines.append(f"<li>{stripped[2:]}</li>")

        # Horizontal rule
        elif stripped in ("---", "***", "___"):
            if in_ul: html_lines.append("</ul>"); in_ul = False
            html_lines.append("<hr>")

        # Blank line
        elif not stripped:
            if in_ul: html_lines.append("</ul>"); in_ul = False
            html_lines.append("")

        # Normal paragraph
        else:
            if in_ul: html_lines.append("</ul>"); in_ul = False
            html_lines.append(f"<p>{stripped}</p>")

    if in_ul:
        html_lines.append("</ul>")

    result = "\n".join(html_lines)
    # Bold: **text** or __text__
    result = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", result)
    result = re.sub(r"__(.+?)__",     r"<strong>\1</strong>", result)
    # Italic
    result = re.sub(r"\*(.+?)\*", r"<em>\1</em>", result)
    return result


def build_and_send(
    emails: list[dict],
    summary_md: str,
    period_start: str,
    period_end: str,
) -> None:
    """Render the newsletter and deliver it via SMTP."""
    summary_html = _markdown_to_html(summary_md)

    html_body = _HTML_TEMPLATE.render(
        subject       = config.NEWSLETTER_SUBJECT,
        period_start  = period_start,
        period_end    = period_end,
        email_count   = len(emails),
        summary_html  = summary_html,
        generated_at  = datetime.now().strftime("%Y-%m-%d %H:%M"),
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = config.NEWSLETTER_SUBJECT
    msg["From"]    = config.SMTP_FROM
    msg["To"]      = ", ".join(config.SMTP_TO)

    # Plain-text fallback
    plain = f"{config.NEWSLETTER_SUBJECT}\n\n{summary_md}"
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    context = ssl.create_default_context()
    with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
        server.ehlo()
        server.starttls(context=context)
        server.login(config.SMTP_USERNAME, config.SMTP_PASSWORD)
        server.sendmail(config.SMTP_FROM, config.SMTP_TO, msg.as_string())

    print(f"[newsletter] Sent to {config.SMTP_TO}")
